version: "3.9"
services:
  kikoeru:
    image: darkxipher/kikoeru
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    ports:
      - '8008:8888'
    volumes:
      - /media/storage2/ASMR:/mnt/Media/Voice
      - /docker/kikoeru/db.sqlite3:/opt/app/db.sqlite3

